[package]
name = "charred"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charrid = { git = "https://github.com/Endercass/charrid", branch = "master" }
redis = "0.23.0"
tokio = "1.27.0"
